export const FETCH_VAST_REQUEST = 'FETCH_VAST_REQUEST';
export const FETCH_VAST_SUCCESS = 'FETCH_VAST_SUCCESS';
export const FETCH_VAST_FAILURE = 'FETCH_VAST_FAILURE';

export const CREATE_VAST_REQUEST = 'CREATE_VAST_REQUEST';
export const CREATE_VAST_SUCCESS = 'CREATE_VAST_SUCCESS';
export const CREATE_VAST_FAILURE = 'CREATE_VAST_FAILURE';

export const EDIT_VAST_REQUEST = 'EDIT_VAST_REQUEST';
export const EDIT_VAST_SUCCESS = 'EDIT_VAST_SUCCESS';
export const EDIT_VAST_FAILURE = 'EDIT_VAST_FAILURE';
